services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - nestnet
    ports:
      - '27017:27017'
  
  apigateway:
    build:
      context: .
      dockerfile: ./apps/apigateway/Dockerfile
      target: development

    command: npm run start:prod-apigateway
    ports:
      - "3000:3000"
    networks:
      - nestnet
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:prod-auth
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    networks:
      - nestnet
    volumes:
      - .:/usr/src/app

networks:
  nestnet:
    driver: bridge
