services:
  apigateway:
    build:
      context: .
      dockerfile: ./apps/apigateway/Dockerfile
      target: development

    command: npm run start:prod-apigateway
    ports:
      - "3000:3000"
    networks:
      - nestnet
    volumes:
      - .:/usr/src/app
    depends_on:
      - auth

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:prod-auth
    ports:
      - "3001:3000"
    networks:
      - nestnet
    volumes:
      - .:/usr/src/app

networks:
  nestnet:
    driver: bridge
